import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { spaceMono } from '@/app/lib/font'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dev Hunter",
  description: "Generated by DJ Neill",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>{children}</body>
    </html>
  );
}
